import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { useEffect, useState } from 'react'
import AnimeCard from '../components/AnimeCard'
import axios from 'axios'

export default function Home() {
  type Seasons = 'winter' | 'spring' | 'fall' | 'summer'
  const [season, setSeason] = useState<Seasons>('spring')

  const [year, setYear] = useState(2022)
  const [anime, setAnime] = useState([])
  const [page, setPage] = useState(1)
  const [pageCount, setPageCount] = useState(0)
  useEffect(() => {
    axios
      .get(`https://api.jikan.moe/v4/seasons/${year}/${season}?page=${page}`)
      .then((res) => {
        setAnime(res.data.data)
        setPageCount(res.data.pagination.last_visible_page)
      })
      .catch((error) => console.log(error))
  }, [season, year, page])

  const handleClick = (e) => {
    let { year:updatedYear,season:updatedSeason } = JSON.parse(e.target.value)
    setYear(updatedYear)
    setSeason(updatedSeason)
    setPage(1)
  }

  const handlePageClick = (page) => {
    setPage(page)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Hunnimation!</h1>
        <div>
          <button
            name="winter2022"
            value='{"year":2022,"season":"winter"}'
            onClick={(e) => handleClick(e)}
          >
            Winter 2022
          </button>
          <button
            name="spring2022"
            value='{"year":2022,"season":"spring"}'
            onClick={(e) => handleClick(e)}
          >
            Spring 2022
          </button>
          <button
            name="summer2022"
            value='{"year":2022,"season":"summer"}'
            onClick={(e) => handleClick(e)}
          >
            Summer 2022
          </button>
          <button
            name="fall2022"
            value='{"year":2022,"season":"fall"}'
            onClick={(e) => handleClick(e)}
          >
            Fall 2022
          </button>
        </div>
        <div>
          {Array.from(Array(pageCount).keys()).map((page) => 
          <button onClick ={() => handlePageClick(page + 1)} >
            {page + 1}
          </button>
          )}
        </div>
        <div className={styles.grid}>
          {anime.map((anime) => (
            <AnimeCard
              image={anime.images.jpg.image_url}
              genre={anime.genres}
              episodes={anime}
              titleEng={anime.title_english}
              titleJp={anime.title_japanese}
              synopsis={anime.synopsis}
              score={anime.score}
              studios={anime.studios.map((studio) => studio.name)}
              url={anime.url}
            />
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
